services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - ./data/redis:/data
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: npm run start:dev api-gateway
    ports:
      - '3000:3000'
    env_file:
      - ./apps/api-gateway/.env
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
  # user-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/user-service/Dockerfile
  #     target: development
  #   command: npm run start:dev user-service
  #   env_file:
  #     - ./apps/user-service/.env
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  # book-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/book-service/Dockerfile
  #     target: development
  #   command: npm run start:dev book-service
  #   env_file:
  #     - ./apps/book-service/.env
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  # cart-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/cart-service/Dockerfile
  #     target: development
  #   command: npm run start:dev cart-service
  #   env_file:
  #     - ./apps/cart-service/.env
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  # rating-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/rating-service/Dockerfile
  #     target: development
  #   command: npm run start:dev rating-service
  #   env_file:
  #     - ./apps/rating-service/.env
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  # order-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/order-service/Dockerfile
  #     target: development
  #   command: npm run start:dev order-service
  #   env_file:
  #     - ./apps/order-service/.env
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  # wishlist-service:
  #   build:
  #     context: .
  #     dockerfile: ./apps/wishlist-service/Dockerfile
  #     target: development
  #   command: npm run start:dev wishlist-service
  #   env_file:
  #     - ./apps/wishlist-service/.env
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
